### PR TITLE
Chris branch

### PR DESCRIPTION
**Pull request by chrischandfw**

### CODE REVIEW

**Review by Kevin-Roney — APPROVED** [review]
Great work on the fetch-utils!

**Review by taha-amin — APPROVED** [review]
looks great Chris!

**Review by delaneyfogarty — APPROVED** [review]
doing great!

**Review by ElliottProductions — COMMENTED** [review]
Great job! You're getting a raise!

**Review by ElliottProductions — COMMENTED** [review]
Excellent work! Pizza party time

**Pull request merged**
