### PR TITLE
Added render-utils.js and renderMessages function

### PR DESCRIPTION
**Pull request by Kevin-Roney**

### CODE REVIEW

**Review by taha-amin — APPROVED** [review]
lookin good

**Review by delaneyfogarty — APPROVED** [review]
nice!

**Review by chrischandfw — APPROVED** [review]
Super!

**Review by chrischandfw — COMMENTED** [review]
Nice jobbin!

**Review by chrischandfw — COMMENTED** [review]
Nice jobbin!

**Pull request merged**
